modLoader="javafml"
loaderVersion="[34,)"
license="GNU"

[[mods]]
modId="cfm"
version="7.0.0-pre19"
displayName="MrCrayfish's Furniture Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cfm/update.json"
displayURL="https://mrcrayfish.com/mods?id=cfm"
logoFile="furniture.png"
credits=""
authors="MrCrayfish"
description="Adds over 80 unique pieces of furniture to the game"
itemIcon="cfm:stripped_oak_chair"
configBackground="minecraft:textures/block/stripped_oak_log.png"

[[dependencies.cfm]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cfm]]
    modId="filters"
    mandatory=false
    versionRange="[1.1.1,)"
    ordering="AFTER"
    side="CLIENT"