modLoader="javafml"
loaderVersion="[39,)"
license="GPLv3"
issueTrackerURL="https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues"

[[mods]]
modId="cfm"
version="7.0.0-pre35"
displayName="MrCrayfish's Furniture Mod"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=cfm"
displayURL="https://mrcrayfish.com/mods?id=cfm"
logoFile="furniture.png"
credits="The people who helped me when I first started creating mods. I wouldn't be here without them!"
authors="MrCrayfish"
description="MrCrayfish's Furniture Mod is all about adding functioning furniture and decorations. This mod currently adds over eighty unique blocks and is continuely growing with new updates."

[[dependencies.cfm]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.cfm]
    catalogueItemIcon="cfm:stripped_oak_chair"
    configuredBackground="minecraft:textures/block/stripped_oak_log.png"