modLoader="javafml"
loaderVersion="[30,)"

[[mods]]
modId="cfm"
version="7.0.0-pre15"
displayName="MrCrayfish's Furniture Mod"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cfm/update.json"
displayURL="https://mrcrayfish.com/mods?id=cfm"
logoFile="furniture.png"
credits=""
authors="MrCrayfish"
description="Adds over 80 unique pieces of furniture to the game"

[[dependencies.cfm]]
    modId="forge"
    mandatory=true
    versionRange="[30.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cfm]]
    modId="filters"
    mandatory=false
    versionRange="[1.1.1,)"
    ordering="AFTER"
    side="CLIENT"